### ISSUE TITLE
ChartLine empty when first 2 values are 0 & XAxis values

### ISSUE THREAD

**Issue by amanfromfrance** [EvotecIT/PSWriteHTML#235]
Hello PrzemyslawKlys,

I am opening an issue on GitHub so that my problem is easier to track (sorry for my emails).

I am trying to plot line charts and while it was working as expected using the old "**Dashimo**" module, I've noticed that now with "**PSWriteHTML**" I have an issue with the data that is set as the ChartLine values.

For example in the code below the 2 first values are **0s**:

```powershell
$test = @(
@{date="May  4"; time="00:02:47"; participantNumber=0}
@{date="May  4"; time="00:07:47"; participantNumber=0}
@{date="May  4"; time="00:12:47"; participantNumber=3}
@{date="May  4"; time="00:17:47"; participantNumber=2}
@{date="May  4"; time="00:22:47"; participantNumber=1}
@{date="May  4"; time="00:27:47"; participantNumber=2}
@{date="May  4"; time="00:32:47"; participantNumber=3}
@{date="May  4"; time="00:37:47"; participantNumber=4}
@{date="May  4"; time="00:42:47"; participantNumber=5}
@{date="May  4"; time="00:47:47"; participantNumber=10})

New-HTML -TitleText 'Charts - TimeLine' -Online -FilePath "C:\ChartLine.html" {
	New-HTMLSection  -Name 'Total number of Calls' -Collapsable -TextBackGroundColor "#000000" -TextColor "#ff7900" {
		New-HTMLPanel -Invisible {
			New-HTMLChart {
				New-ChartAxisX -Name $test.time
				ChartLegend -Name 'Calls Number'
				New-ChartLine -Name 'Participants Number' -Value $test.participantNumber -Color "#ff7900" 
				New-ChartAxisY -Show -TitleText 'Time'
			}
		}
	}
}
```

Instead of the line chart I see only one plot:

![2021-05-05_100738](https://user-images.githubusercontent.com/58064665/117112767-d9bb7d00-ad89-11eb-90d7-972bc30d5008.png)

If I replace the 2 first values with digits greater than 0:

```powershell
$test = @(
@{date="May  4"; time="00:02:47"; participantNumber=5}
@{date="May  4"; time="00:07:47"; participantNumber=4}
@{date="May  4"; time="00:12:47"; participantNumber=3}
@{date="May  4"; time="00:17:47"; participantNumber=2}
@{date="May  4"; time="00:22:47"; participantNumber=1}
@{date="May  4"; time="00:27:47"; participantNumber=2}
@{date="May  4"; time="00:32:47"; participantNumber=3}
@{date="May  4"; time="00:37:47"; participantNumber=4}
@{date="May  4"; time="00:42:47"; participantNumber=5}
@{date="May  4"; time="00:47:47"; participantNumber=10})
```

Now the graph displays:

![2021-05-05_100512](https://user-images.githubusercontent.com/58064665/117112846-f5268800-ad89-11eb-9d99-50767a50eaaa.png)

However, the time values are replaced by an index value and everything I tried was unsuccessful.

Thanks!

**Comment by PrzemyslawKlys** [comment]
Try giving a type

```
   New-ChartAxisX -Name $test.time -Type datetime
```

**Comment by PrzemyslawKlys** [comment]
Your problems with zeros is the same as https://github.com/EvotecIT/PSWriteHTML/issues/234 and it's now fixed in sources and it will be released to preview later on today

**Comment by amanfromfrance** [comment]
Thanks for your feedback **PrzemyslawKlys**!
> 
> 
> Try giving a type
> 
> ```powershell
>    New-ChartAxisX -Name $test.time -Type datetime
> ```

I have tried this with no sucess, I still see the index values.

I saw what you explained in #234 and tried to install the pre-release module using your command:

```powershell
Install-Module PSWriteHTML -AllowPrerelease
```

With this version I only get empty charts:

![image](https://user-images.githubusercontent.com/58064665/117123311-29547580-ad97-11eb-8cae-40228ff5382c.png)

**Comment by PrzemyslawKlys** [comment]
Nah, it's not released with a fix for you. But once I release it, it should work.

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/117127718-c36aec80-ad9c-11eb-8cdc-072a147e62ab.png)

That's what I get on my version:

```powershell
Import-Module .\PSWriteHTML.psd1 -Force

$test = @(
    @{date = "May  4"; time = "00:02:47"; participantNumber = 0 }
    @{date = "May  4"; time = "00:07:47"; participantNumber = 0 }
    @{date = "May  4"; time = "00:12:47"; participantNumber = 3 }
    @{date = "May  4"; time = "00:17:47"; participantNumber = 2 }
    @{date = "May  4"; time = "00:22:47"; participantNumber = 1 }
    @{date = "May  4"; time = "00:27:47"; participantNumber = 2 }
    @{date = "May  4"; time = "00:32:47"; participantNumber = 3 }
    @{date = "May  4"; time = "00:37:47"; participantNumber = 4 }
    @{date = "May  4"; time = "00:42:47"; participantNumber = 5 }
    @{date = "May  4"; time = "00:47:47"; participantNumber = 10 })

New-HTML -TitleText 'Charts - TimeLine' -Online -FilePath "$PSScriptRoot\Example-ChartsLine1.html" {
    New-HTMLSection -Name 'Total number of Calls' -Collapsable -TextBackGroundColor "#000000" -TextColor "#ff7900" {
        New-HTMLPanel -Invisible {
            New-HTMLChart {
                New-ChartAxisX -Name $test.time
                ChartLegend -Name 'Calls Number'
                New-ChartLine -Name 'Participants Number' -Value $test.participantNumber -Color "#ff7900"
                New-ChartAxisY -Show -TitleText 'Time'
            }
        }
    }
} -ShowHTML
```

**Comment by PrzemyslawKlys** [comment]
You can try it yourself, now. 

```powershell
Install-Module PSWriteHTML -AllowPrerelease
```

**Comment by amanfromfrance** [comment]
indeed, now it works! Thanks for your support **PrzemyslawKlys**!
